# Generated by Django 5.2.5 on 2025-08-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balloon', '0004_client_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('volume', models.IntegerField(verbose_name='Обьем')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon.client', verbose_name='Клиент')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon.balloontype', verbose_name='Тип баллона')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренда',
            },
        ),
    ]
