# Generated by Django 5.2.5 on 2025-08-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalloonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование типа баллона')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер баллона')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/balloon')),
                ('produced_at', models.DateField(verbose_name='Дата производства баллона')),
                ('volume', models.IntegerField(verbose_name='обьем баллона')),
                ('status', models.CharField(choices=[('EMPTY', 'Принят пустой'), ('AT-REFUELING', 'Отправлен на заправку'), ('ACCEPTED-FULL', 'Принят полный'), ('AT-OWNER', 'У владельца')], default='EMPTY', max_length=14, verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon.balloontype', verbose_name='Тип баллона')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloon.client', verbose_name='Владелец баллона')),
            ],
        ),
    ]
