# Generated by Django 5.2.5 on 2025-08-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balloontype',
            options={'verbose_name': 'Тип баллона'},
        ),
    ]
