# Generated by Django 5.2.5 on 2025-08-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0002_alter_balloontype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balloon',
            options={'verbose_name': 'Баллон', 'verbose_name_plural': 'Баллоны'},
        ),
        migrations.AlterModelOptions(
            name='balloontype',
            options={'verbose_name': 'Тип баллона', 'verbose_name_plural': 'Тип баллонов'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
