# Generated by Django 5.2.5 on 2025-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0003_alter_balloon_options_alter_balloontype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название фирмы'),
        ),
    ]
